# Generated by Django 3.2.13 on 2022-05-23 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0002_post_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='material',
            field=models.CharField(default='acrylics on canvas', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='completed_on',
            field=models.DateField(),
        ),
    ]
