# Generated by Django 3.2.13 on 2022-05-30 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0002_mailinglist'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailinglist',
            name='no_dont_join',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mailinglist',
            name='yes_join',
            field=models.BooleanField(default=True),
        ),
    ]
