# Generated by Django 3.2.13 on 2022-05-23 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0003_auto_20220523_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='material',
            field=models.CharField(default='acrylics_on_canvas', max_length=100, unique=True),
        ),
    ]
