# Generated by Django 3.2.13 on 2022-05-23 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0006_alter_post_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='material',
        ),
    ]
